import type { ExerciseProgressCard } from "./types";

export const PERFORMANCE_DEMO_CARDS: ExerciseProgressCard[] = [
  {
    exerciseId: "bench-press",
    exerciseName: "Bench Press",
    unitLabel: "KG",
    sessionsLogged: 6,
    lastTrainedAt: "2026-03-10T10:00:00.000Z",
    bestWeight: 72.5,
    bestReps: 8,
    bestVolume: 580,
    latestSession: {
      sessionId: "s1",
      completedAt: "2026-03-10T10:00:00.000Z",
      status: "completed",
      completedSets: 4,
      totalSetsPlanned: 4,
      sessionVolume: 1450,
    },
    trend: {
      result: "better",
      improvedSets: 2,
      matchedSets: 1,
      belowSets: 0,
      prCount: 1,
    },
    recentDelta: {
      weight: 2.5,
      reps: 0,
      volume: 60,
    },
  },
  {
    exerciseId: "back-squat",
    exerciseName: "Back Squat",
    unitLabel: "KG",
    sessionsLogged: 6,
    lastTrainedAt: "2026-03-11T10:00:00.000Z",
    bestWeight: 95,
    bestReps: 6,
    bestVolume: 760,
    latestSession: {
      sessionId: "s2",
      completedAt: "2026-03-11T10:00:00.000Z",
      status: "completed",
      completedSets: 4,
      totalSetsPlanned: 4,
      sessionVolume: 1820,
    },
    trend: {
      result: "better",
      improvedSets: 3,
      matchedSets: 0,
      belowSets: 0,
      prCount: 1,
    },
    recentDelta: {
      weight: 5,
      reps: 0,
      volume: 110,
    },
  },
  {
    exerciseId: "romanian-deadlift",
    exerciseName: "Romanian Deadlift",
    unitLabel: "KG",
    sessionsLogged: 5,
    lastTrainedAt: "2026-03-11T10:00:00.000Z",
    bestWeight: 82.5,
    bestReps: 10,
    bestVolume: 660,
    latestSession: {
      sessionId: "s3",
      completedAt: "2026-03-11T10:00:00.000Z",
      status: "completed",
      completedSets: 3,
      totalSetsPlanned: 3,
      sessionVolume: 1485,
    },
    trend: {
      result: "same",
      improvedSets: 0,
      matchedSets: 2,
      belowSets: 0,
      prCount: 0,
    },
    recentDelta: {
      weight: 0,
      reps: 0,
      volume: 0,
    },
  },
  {
    exerciseId: "incline-press",
    exerciseName: "Incline Press",
    unitLabel: "KG",
    sessionsLogged: 4,
    lastTrainedAt: "2026-03-13T10:00:00.000Z",
    bestWeight: 65,
    bestReps: 8,
    bestVolume: 520,
    latestSession: {
      sessionId: "s4",
      completedAt: "2026-03-13T10:00:00.000Z",
      status: "partial",
      completedSets: 3,
      totalSetsPlanned: 4,
      sessionVolume: 975,
    },
    trend: {
      result: "mixed",
      improvedSets: 1,
      matchedSets: 1,
      belowSets: 1,
      prCount: 0,
    },
    recentDelta: {
      weight: 2.5,
      reps: -1,
      volume: 20,
    },
  },
];